language: cpp

dist: xenial

branches:
  except:
  - gh-pages
  - single_header

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
- sudo pip install mkdocs

script:
    - mkdir _bld
    - cd _bld
    - cmake -DVECPP_BUILD_SINGLE_HEADER=ON ..
    - cmake --build .
    - ctest --output-on-failure
    - cd ..
    - mkdocs build --verbose --clean --strict
    - mkdir include_single
    - cp include/vecpp/vecpp_single.h include_single/

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
   local_dir: site
   keep-history: true
   on:
     branch: master
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
   local_dir: include_single
   keep-history: true
   target-branch: single_header
   on:
     branch: master

notifications:
  email: false
