skip_tags: true
matrix:
    fast_finish: true
image: Visual Studio 2017
build_script:
    - git submodule init
    - git submodule update
    - mkdir _bld
    - cd _bld
    - cmake -G "Visual Studio 15 2017" -DVECPP_BUILD_SINGLE_HEADER=ON ..
    - cmake --build .
    - ctest