site_name: VecPP documentation
use_directory_urls: false

nav:
  - Home: index.md
  - Dev Guide: dev-guide/index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Performance: user-guide/performance.md
  - Reference guide:
    - Home: reference/index.md
    - Angle: reference/angle/index.md
    - Vector: reference/vec/index.md
    - Matrix: reference/mat/index.md