site_name: VecPP documentation

nav:
  - Home: index.md
  - Dev Guide: dev-guide/index.md
  - User Guide:
    - Installation: user-guide/installation.md
  - Reference guide:
    - Angle: reference/angle.md
    - Vector: reference/vec.md