workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - single_header
          
version: 2
jobs:
  build:
    docker:
      - image: francoischabot/build_env
    steps:
      - checkout
      - run: git submodule update --init && mkdir test-reports
      - run:
          name: Prepare DEBUG
          command: |
            mkdir _bld && cd _bld
            cmake -DCMAKE_BUILD_TYPE=DEBUG -DVECPP_BUILD_TESTS=ON -DVECPP_BUILD_SINGLE_HEADER=ON ..
            make -j2
      - run:
          name: Prepare RELEASE
          command: |
            mkdir _bld_rel && cd _bld_rel
            cmake -DCMAKE_BUILD_TYPE=RELEASE -DVECPP_BUILD_TESTS=ON -DVECPP_BUILD_SINGLE_HEADER=ON ..
            make -j2

      - run:
          name: Build DEBUG
          command: cd _bld && make -j2
      - run:
          name: Build RELEASE
          command: cd _bld_rel && make -j2

      - run:
        name: Test DEBUG
        command: |
          ./_bld/tests/all_tests -r xml -o test-reports/debug.xml
          ./_bld/tests/all_tests_sh -r xml -o test-reports/debug-single-header.xml
      - run:
        name: Test RELEASE
        command: |
          ./_bld_rel/tests/all_tests -r xml -o test-reports/release.xml
          ./_bld_rel/tests/all_tests_sh -r xml -o test-reports/release-single-header.xml

      - store_test_results:
          path: test-reports/